<?php
echo "<div class='modal fade' id='addBookModal' tabindex='-1' role='dialog' aria-labelledby='addBookModalLabel' aria-hidden='true'>";
echo "<div class='modal-dialog' role='document'>";
echo "<div class='modal-content'>";
echo "<div class='modal-header'>";
echo "<h5 class='modal-title' id='addBookModalLabel'>Add New Book</h5>";
echo "<button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
echo "<span aria-hidden='true'>&times;</span>";
echo "</button>";
echo "</div>";
echo "<div class='modal-body'>";
echo "<form action='add_book.php' method='POST'>";
echo "<div class='form-group'>";
echo "<label for='isbn'>ISBN</label>";
echo "<input type='text' class='form-control' id='isbn' name='isbn' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='title'>Title</label>";
echo "<input type='text' class='form-control' id='title' name='title' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='author'>Author</label>";
echo "<input type='text' class='form-control' id='author' name='author_id' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='genre'>Genre</label>";
echo "<input type='text' class='form-control' id='genre' name='genre_id' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='publication_date'>Publication Date</label>";
echo "<input type='date' class='form-control' id='publication_date' name='publication_date' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='availability_status'>Availability Status</label>";
echo "<input type='text' class='form-control' id='availability_status' name='availability_status' required>";
echo "</div>";
echo "<button type='submit' class='btn btn-primary'>Add Book</button>";
echo "</form>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";
?>