<?php
echo "<div class='modal fade' id='addFineModal' tabindex='-1' role='dialog' aria-labelledby='addFineModalLabel' aria-hidden='true'>";;
echo "<div class='modal-dialog' role='document'>";;
echo "<div class='modal-content'>";;
echo "<div class='modal-header'>";;
echo "<h5 class='modal-title' id='addFineModalLabel'>Add New Fine</h5>";
echo "<button type='button' class='close' data-dismiss='modal' aria-label='Close'>";
echo "<span aria-hidden='true'>&times;</span>";
echo "</button>";
echo "</div>";
echo "<div class='modal-body'>";
echo "<form action='add_fine.php' method='POST'>";
echo "<div class='form-group'>";
echo "<label for='member'>Member ID</label>";
echo "<input type='text' class='form-control' id='member' name='member_id' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='amount'>Amount</label>";
echo "<input type='text' class='form-control' id='amount' name='amount' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='reason'>Reason</label>";
echo "<input type='text' class='form-control' id='reason' name='reason' required>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label for='payment_status'>Payment Status</label>";
echo "<input type='text' class='form-control' id='payment_status' name='payment_status' required>";
echo "</div>";
echo "<button type='submit' class='btn btn-primary'>Add Fine</button>";
echo "</form>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";
?>